# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  - job_name: 'vmagent'
    static_configs:
      - targets: ['vmagent:8429']
  - job_name: 'victoriametrics'
    static_configs:
      - targets: ['victoriametrics:8428']
  - job_name: 'node_exporter'
    static_configs:
      - targets:
          ['https://node.webhook.pp.ua']
  - job_name: 'bots-env'
    static_configs:
      - targets:
          ['grafana:3000', 'https://metrics.webhook.pp.ua']
